init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
  - cmd: java -version

# test_script:
#   - mvn test
# build: off
build_script:
# after_build:
  - util/publish-snapshot-on-commit.sh
  - util/generate-latest-docs.sh