init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
  - cmd: java -version

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/74d33a22fbfb1942920e
    on_build_success: false  
    on_build_failure: true


cache:
  - '%HOME%\.m2' 


# test_script:
#   - mvn test
# build: off
# after_build:
build_script:
  - util/forwin.bat
#   - util/publish-snapshot-on-commit.sh
#   - util/generate-latest-docs.sh
build: off
